version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/3.12.8"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "develop"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]